#!/usr/bin/env bash
# gum_theme.sh - Catppuccin Frappe theme configuration for gum
# Part of the modular dotfiles installation system

# Catppuccin Frappe Palette
export COLOR_ROSEWATER="#F2D5CF"
export COLOR_FLAMINGO="#EEBEBE"
export COLOR_PINK="#F4B8E4"
export COLOR_MAUVE="#CA9EE6"
export COLOR_RED="#E78284"
export COLOR_MAROON="#EA999C"
export COLOR_PEACH="#EF9F76"
export COLOR_YELLOW="#E5C890"
export COLOR_GREEN="#A6D189"
export COLOR_TEAL="#81C8BE"
export COLOR_SKY="#99D1DB"
export COLOR_SAPPHIRE="#85C1DC"
export COLOR_BLUE="#8CAAEE"
export COLOR_LAVENDER="#BABBF1"
export COLOR_TEXT="#C6D0F5"
export COLOR_SUBTEXT1="#B5BFE2"
export COLOR_BASE="#303446"
export COLOR_MANTLE="#292C3C"
export COLOR_CRUST="#232634"

# Gum Configuration
# Note: GUM_OPTS is not a valid environment variable in gum
# Cursor colors are set per-command using --cursor.foreground flag

# Input
export GUM_INPUT_CURSOR_FOREGROUND="$COLOR_ROSEWATER"
export GUM_INPUT_PROMPT_FOREGROUND="$COLOR_MAUVE"
export GUM_INPUT_PLACEHOLDER_FOREGROUND="$COLOR_SUBTEXT1"
export GUM_INPUT_WIDTH=80

# Confirm
export GUM_CONFIRM_PROMPT_FOREGROUND="$COLOR_MAUVE"
export GUM_CONFIRM_SELECTED_BACKGROUND="$COLOR_LAVENDER"
export GUM_CONFIRM_SELECTED_FOREGROUND="$COLOR_BASE"
export GUM_CONFIRM_UNSELECTED_BACKGROUND="$COLOR_BASE"
export GUM_CONFIRM_UNSELECTED_FOREGROUND="$COLOR_TEXT"

# Choose
export GUM_CHOOSE_CURSOR_FOREGROUND="$COLOR_ROSEWATER"
export GUM_CHOOSE_HEADER_FOREGROUND="$COLOR_MAUVE"
export GUM_CHOOSE_ITEM_FOREGROUND="$COLOR_TEXT"
export GUM_CHOOSE_SELECTED_FOREGROUND="$COLOR_LAVENDER"

# Spin
export GUM_SPIN_SPINNER_FOREGROUND="$COLOR_ROSEWATER"
export GUM_SPIN_TITLE_FOREGROUND="$COLOR_TEXT"

# Style (General borders)
export GUM_STYLE_BORDER="rounded"
export GUM_STYLE_BORDER_FOREGROUND="$COLOR_LAVENDER"
export GUM_STYLE_ALIGN="left"
export GUM_STYLE_PADDING="1 2"

# Filter
export GUM_FILTER_INDICATOR_FOREGROUND="$COLOR_ROSEWATER"
export GUM_FILTER_MATCH_FOREGROUND="$COLOR_YELLOW"
export GUM_FILTER_PROMPT_FOREGROUND="$COLOR_MAUVE"
export GUM_FILTER_TEXT_FOREGROUND="$COLOR_TEXT"

# Note: GUM_FORMAT_THEME is not a standard gum environment variable
# Format command uses --theme flag directly if needed
